### ISSUE TITLE
sumo-bandplot --project gives IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by JaafarMehrez** [SMTG-UCL/sumo#110]
**First of all, i would like to thank the contributors for such helpful tool. I have calculated the band structure of a spin-polarized monolayer system (MoTe2), after successfully plotting the band structure, I wanted to project orbital contribution onto the band structure using (--project argument) and i got the following error: **

`Traceback (most recent call last):
  File "./sumo-bandplot", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.7/site-packages/sumo/cli/bandplot.py", line 562, in main
    dpi=args.dpi, fonts=args.font)
  File "/root/.local/lib/python3.7/site-packages/sumo/cli/bandplot.py", line 306, in bandplot
    no_base_style=no_base_style, spin=spin)
  File "/root/.local/lib/python3.7/site-packages/sumo/plotting/__init__.py", line 61, in wrapper
    return get_plot(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/sumo/plotting/bs_plotter.py", line 426, in get_projected_plot
    lc = rgbline(distances, bands, weights[0], weights[1],
IndexError: index 1 is out of bounds for axis 0 with size 1
`

**Comment by ajjackson** [comment]
Hi Jaafer,

this looks a lot like https://github.com/SMTG-UCL/sumo/issues/79 , can you check if the advice there helps?

**Comment by JaafarMehrez** [comment]
Thanks sir Adam for your reply, the problem is solved.
