### ISSUE TITLE
error in bandplot (Stacked Mode)

### ISSUE THREAD

**Issue by muhsaj** [SMTG-UCL/sumo#123]
Dear All,
I started using SUMO and came across an error upon running the command "sumo-bandplot --project Cs.s,Pt.d,I.p --mode stacked --circle-size 90". My KPOINTS file is 
K-Points
30
line
reciprocal
        0.00000000000  0.00000000000  0.00000000000 1 G
        0.50000000000  0.00000000000  0.50000000000 1 X

        0.50000000000  0.00000000000  0.50000000000 1 X
        0.62500000000  0.25000000000  0.62500000000 1 U
 
        0.62500000000  0.25000000000  0.62500000000 1 U
        0.37500000000  0.37500000000  0.75000000000 1 K

and the error is 
Traceback (most recent call last):
  File "/home/muhsaj/.local/bin/sumo-bandplot", line 8, in <module>
    sys.exit(main())
  File "/home/muhsaj/.local/lib/python3.7/site-packages/sumo/cli/bandplot.py", line 582, in main
    dpi=args.dpi, fonts=args.font)
  File "/home/muhsaj/.local/lib/python3.7/site-packages/sumo/cli/bandplot.py", line 326, in bandplot
    no_base_style=no_base_style, spin=spin)
  File "/home/muhsaj/.local/lib/python3.7/site-packages/sumo/plotting/__init__.py", line 61, in wrapper
    return get_plot(*args, **kwargs)
  File "/home/muhsaj/.local/lib/python3.7/site-packages/sumo/plotting/bs_plotter.py", line 418, in get_projected_plot
    fill_value="extrapolate")(temp_dists)
  File "/home/muhsaj/.local/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 537, in __init__
    "least %d entries" % minval)
ValueError: x and y arrays must have at least 2 entries

Can you please suggest how to overcome the said error?

Best Regards,
Muhammad

**Comment by utf** [comment]
Thank you for raising this error.

This has now been fixed.
