### ISSUE TITLE
sumo-bandplot memory error

### ISSUE THREAD

**Issue by etmCc** [SMTG-UCL/sumo#130]
Trying to execute sumo-bandplot gave a memory error. Discussion with @utf pointed out that this indicates the node doesn't have enough memory to load vasprun.xml; I was able to ssh vasprun.xml and KPOINTS to my local machine and was able to run as expected.

vasprun.xml was 2.9GB; the largest size I know worked as expected on the cluster was 1.3GB.
This issue occurred on TACC/Stampede2.

```
$ sumo-bandplot --band-edges
MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home1/07440/tg867393/.local/bin/sumo-bandplot", line 8, in <module>
    sys.exit(main())
  File "/home1/07440/tg867393/.local/lib/python3.7/site-packages/sumo/cli/bandplot.py", line 629, in main
    dpi=args.dpi, fonts=args.font)
  File "/home1/07440/tg867393/.local/lib/python3.7/site-packages/sumo/cli/bandplot.py", line 247, in bandplot
    vr = BSVasprun(vr_file, parse_projected_eigen=parse_projected)
  File "/home1/07440/tg867393/.local/lib/python3.7/site-packages/pymatgen/io/vasp/outputs.py", line 1525, in __init__
    for event, elem in ET.iterparse(f):
MemoryError
```

**Comment by ajjackson** [comment]
That's a pretty chunky vasprun! In principle it is possible to save memory by reading the XML file progressively without loading the whole thing into memory. Indeed, I was under the impression BSVasprun, the pymatgen class we use here, was supposed to do that. It might be worth asking Pymatgen to look into whether this is working properly with your file.

**Comment by ajjackson** [comment]
Closing due to inactivity - in any case I think this is one for upstream (i.e. Pymatgen).

Good luck with your huge calculations, it sounds fun!
