### ISSUE TITLE
sumo-optplot failed to plot optical absorption spectra diagrams.

### ISSUE THREAD

**Issue by hongyi-zhao** [SMTG-UCL/sumo#221]
I try to test sumo-optplot using the calculation results of [Dielectric_properties_of_Si_using_BSE](https://www.vasp.at/wiki/index.php/Dielectric_properties_of_Si_using_BSE), but failed as follows:

```shell
(datasci) werner@X10DAi:~/Downloads/GW_BSE/Si_BSE$ sumo-optplot 
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/bin/sumo-optplot", line 33, in <module>
    sys.exit(load_entry_point('sumo', 'console_scripts', 'sumo-optplot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/Public/repo/github.com/SMTG-UCL/sumo.git/sumo/cli/optplot.py", line 455, in main
    optplot(
  File "/home/werner/Public/repo/github.com/SMTG-UCL/sumo.git/sumo/cli/optplot.py", line 170, in optplot
    latexify(vr.final_structure.composition.reduced_formula).replace(
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'Vasprun' object has no attribute 'final_structure'. Did you mean: 'initial_structure'?


(datasci) werner@X10DAi:~/Downloads/GW_BSE/Si_BSE$ sumo-optplot ./vasprun.xml
usage: sumo-optplot [-h] [-f F [F ...]] [-p P] [-d D] [-c C [C ...]] [-g G] [-b [E ...]]
                    [-l L [L ...]] [-a] [--height HEIGHT] [--width WIDTH] [--xmin XMIN] [--xmax XMAX]
                    [--ymin YMIN [YMIN ...]] [--ymax YMAX [YMAX ...]] [--style STYLE [STYLE ...]]
                    [--no-base-style] [--format FORMAT] [--dpi DPI] [--font FONT] [--units UNITS]
                    [M ...]
sumo-optplot: error: argument M: invalid choice: './vasprun.xml' (choose from 'eps_real', 'absorption', 'n_real', 'n_imag', 'loss', 'eps_imag')
```

I attached the vasprun.xml file below.

[vasprun.zip](https://github.com/SMTG-UCL/sumo/files/12246634/vasprun.zip)

Regards,
Zhao

**Comment by utf** [comment]
`sumo-optplot`automatically looks for the vasprun in the current directory. If you want to specify the file explicitly you need to use the `-f` option. E.g., `sumo-optplot -f vasprun.xml`. See the docs for more details: https://smtg-ucl.github.io/sumo/sumo-optplot.html

**Comment by utf** [comment]
I just realised I only responded to your second issue. I will look into the first one.

**Comment by hongyi-zhao** [comment]
> `sumo-optplot`automatically looks for the vasprun in the current directory. If you want to specify the file explicitly you need to use the `-f` option. E.g., `sumo-optplot -f vasprun.xml`. See the docs for more details: https://smtg-ucl.github.io/sumo/sumo-optplot.html



This cannot solve the problem, as shown below:

```shell
(datasci) werner@X10DAi:~/Downloads/GW_BSE/Si_BSE$ sumo-optplot -f vasprun.xml
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/bin/sumo-optplot", line 33, in <module>
    sys.exit(load_entry_point('sumo', 'console_scripts', 'sumo-optplot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/Public/repo/github.com/SMTG-UCL/sumo.git/sumo/cli/optplot.py", line 455, in main
    optplot(
  File "/home/werner/Public/repo/github.com/SMTG-UCL/sumo.git/sumo/cli/optplot.py", line 170, in optplot
    latexify(vr.final_structure.composition.reduced_formula).replace(
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'Vasprun' object has no attribute 'final_structure'. Did you mean: 'initial_structure'?

```

**Comment by utf** [comment]
The VASP output is for a GW BSE calculation. I guess that includes different outputs than a regular optics calculation. I don't have much experience in them though.

**Comment by ajjackson** [comment]
Ah right. I started a branch to implement some of these other dielectric function calculations a few years ago but didn't have much incentive to work on it after leaving UCL :laughing: 

https://github.com/SMTG-UCL/sumo/pull/48

**Comment by hongyi-zhao** [comment]
So, I must first confirm the current problem lies in sumo or Pymatgen. If it's the latter, I should submit a bug report there

**Comment by hongyi-zhao** [comment]
> Taking a look at the Pymatgen code: the Vasprun parser has lots of places that assume `final_structure` has been set, but it is only set under certain conditions when the relevant data is found in the file: https://github.com/materialsproject/pymatgen/blob/6d1ffa40123f4f714323f4308418b4062d422d65/pymatgen/io/vasp/outputs.py#L475
> 
> So if your Vasprun object does not have a `final_structure` attribute, this means that either:
> 
>     * your calculation output is invalid (did it terminate succesfully?), or
> 
>     * there exist valid outputs that don't have "finalpos" structure block. (i.e. a bug in Pymatgen, which assumes that they always do.)

See [the comment](https://github.com/materialsproject/pymatgen/issues/3213#issuecomment-1664946086) given by @shyuep below:

> I don't think a final_structure even makes sense in a GW_BSE calculation isn't it? It only makes sense in a relaxation. This is not a bug. It simply means the calculation does not change the position of the atoms.

**Comment by ajjackson** [comment]
Well, the line of code triggering the error here is only responsible for getting the chemical formula anyway. So Sumo could possibly be made more robust against this specific situation.

As far as I can tell from the code, many attributes of the Pymatgen Vasprun object such CompleteDos, get_computed_entry(), get_band_structure() ... will attempt to access `self.final_structure` regardless of whether it "makes sense".

**Comment by shyuep** [comment]
In any case, I have just pushed a fix that makes sure Vasprun.final_structure == Vasprun.initial_structure if there is no relaxation.

**Comment by utf** [comment]
Agreed that using `initial_structure` is the better way to go, and we should probably update sumo to use that. But thanks for the fix @shyuep.

**Comment by ajjackson** [comment]
That sounds great, hopefully the upstream fix will prevent the same issue being hit for other properties.

**Comment by hongyi-zhao** [comment]
Now, it works, but even I use the `-a` option, it still generates only one plot, as shown below:

```
$ sumo-optplot -a -f ./vasprun.xml 
```
![image](https://github.com/SMTG-UCL/sumo/assets/11155854/9f36e31b-4229-4f16-b7f7-5e0f94a9ae68)

**Comment by ajjackson** [comment]
Is the data for xx, yy, zz different in the file? It looks like it plotted all three but they were identical.

**Comment by hongyi-zhao** [comment]
It seems that your conjecture is correct:

```python
In [1]: import pymatgen.io.vasp as vasp
   ...: import numpy as np

In [2]: vr = vasp.Vasprun("sumo/vasprun.xml")
   ...: e2 = np.array(vr.dielectric[2])
   ...: e2x = e2[:, 0]
   ...: e2y = e2[:, 1]
   ...: e2z = e2[:, 2]
/home/werner/Public/hpc/tools/materialsproject/pymatgen.git/pymatgen/io/vasp/outputs.py:1084: UserWarning: No POTCAR file with matching TITEL fields was found in /home/werner/Public/hpc/vasp/learning-by-doing/optical-absorption-spectra/sumo
  warnings.warn(f"No POTCAR file with matching TITEL fields was found in {os.path.abspath(p)}")

In [3]: differences_x_y = [abs(a - b) for a, b in zip(e2x, e2y)]
   ...: differences_y_z = [abs(a - b) for a, b in zip(e2y, e2z)]
   ...: differences_z_x = [abs(a - b) for a, b in zip(e2z, e2x)]
   ...: 

In [4]: max_difference = max(max(differences_x_y), max(differences_y_z), max(differences_z_x))
   ...: min_difference = min(min(differences_x_y), min(differences_y_z), min(differences_z_x))

In [5]: print(f"Maximum absolute difference: {max_difference}")
   ...: print(f"Minimum absolute difference: {min_difference}")
Maximum absolute difference: 0.18339999999999979
Minimum absolute difference: 0.0
```

**Comment by ajjackson** [comment]
Good, good! Then I will close this issue for now.

I suppose we should make a note to update the Pymatgen requirements.
