### ISSUE TITLE
Why  bandplot add --project  error?  

### ISSUE THREAD

**Issue by FINEAR** [SMTG-UCL/sumo#254]
sumo-bandplot --project Cr  --ymin -1.0 --ymax 1.0 --zero-line

Traceback (most recent call last):
  File "/public/home/acboth6nmf/.conda/envs/SUMO/bin/sumo-bandplot", line 8, in <module>
    sys.exit(main())
  File "/public/home/acboth6nmf/.conda/envs/SUMO/lib/python3.8/site-packages/sumo/cli/bandplot.py", line 886, in main
    bandplot(
  File "/public/home/acboth6nmf/.conda/envs/SUMO/lib/python3.8/site-packages/sumo/cli/bandplot.py", line 421, in bandplot
    plt = plotter.get_projected_plot(
  File "/public/home/acboth6nmf/.conda/envs/SUMO/lib/python3.8/site-packages/sumo/plotting/__init__.py", line 62, in wrapper
    return get_plot(*args, **kwargs)
  File "/public/home/acboth6nmf/.conda/envs/SUMO/lib/python3.8/site-packages/sumo/plotting/bs_plotter.py", line 555, in get_projected_plot
    proj = get_projections_by_branches(self.bs, selection, normalise=normalise)
  File "/public/home/acboth6nmf/.conda/envs/SUMO/lib/python3.8/site-packages/sumo/electronic_structure/bandstructure.py", line 68, in get_projections_by_branches
    projections = get_projections(bs, selection, normalise=normalise)
  File "/public/home/acboth6nmf/.conda/envs/SUMO/lib/python3.8/site-packages/sumo/electronic_structure/bandstructure.py", line 153, in get_projections
    el_orb_proj = [
  File "/public/home/acboth6nmf/.conda/envs/SUMO/lib/python3.8/site-packages/sumo/electronic_structure/bandstructure.py", line 154, in <listcomp>
    [all_proj[spin][nb][nk][element][orbital] for nk in range(nkpts)]
  File "/public/home/acboth6nmf/.conda/envs/SUMO/lib/python3.8/site-packages/sumo/electronic_structure/bandstructure.py", line 154, in <listcomp>
    [all_proj[spin][nb][nk][element][orbital] for nk in range(nkpts)]
KeyError: <Spin.up: 1>

Looking forward to your early reply.

**Comment by ajjackson** [comment]
Can you provide input files that reproduce this error, or (preferably) find an example in the Sumo test data?

**Comment by FINEAR** [comment]
[sumo_error_project_band.zip](https://github.com/user-attachments/files/18148557/sumo_error_project_band.zip)
Thank you

> Can you provide input files that reproduce this error, or (preferably) find an example in the Sumo test data?

**Comment by FINEAR** [comment]
@ajjackson

**Comment by ajjackson** [comment]
It looks like there is no orbital projection data in the calculation: LORBIT is commented out in the INCAR.

When Sumo calls `get_projections_on_elements_and_orbitals` from Pymatgen, it returns an empty dictionary.

Try recalculating with LORBIT=11?
