### ISSUE TITLE
sumo-phonon-bandplot with --primitive-axis and --born gives an error

### ISSUE THREAD

**Issue by kinzani** [SMTG-UCL/sumo#57]
`sumo-phonon-bandplot` with `--primitive-axis` and `--born` work fine separately but give an error when used together:

```
sumo-phonon-bandplot --dim 2 2 2 --primitive-axis 0. 0.5 0.5   0.5 0.0 0.5   0.5 0.5  0. --born BORN
Using supercell with dimensions:
	[[2. 0. 0.]
	 [0. 2. 0.]
	 [0. 0. 2.]]

Calculating force constants...
Traceback (most recent call last):
  File "/global/home/users/kinzani/miniconda3/envs/p3/bin/sumo-phonon-bandplot", line 10, in <module>
    sys.exit(main())
  File "/global/home/users/kinzani/miniconda3/envs/p3/lib/python3.6/site-packages/sumo/cli/phonon_bandplot.py", line 414, in main
    eigenvectors=args.eigenvectors, dos=args.dos)
  File "/global/home/users/kinzani/miniconda3/envs/p3/lib/python3.6/site-packages/sumo/cli/phonon_bandplot.py", line 191, in phonon_bandplot
    write_fc=False)
  File "/global/home/users/kinzani/miniconda3/envs/p3/lib/python3.6/site-packages/sumo/phonon/phonopy.py", line 93, in load_phonopy
    phonon.set_nac_params(nac_params)
  File "/global/home/users/kinzani/miniconda3/envs/p3/lib/python3.6/site-packages/phonopy/api_phonopy.py", line 445, in set_nac_params
    self.nac_params = nac_params
  File "/global/home/users/kinzani/miniconda3/envs/p3/lib/python3.6/site-packages/phonopy/api_phonopy.py", line 442, in nac_params
    self._set_dynamical_matrix()
  File "/global/home/users/kinzani/miniconda3/envs/p3/lib/python3.6/site-packages/phonopy/api_phonopy.py", line 2582, in _set_dynamical_matrix
    symprec=self._symprec)
  File "/global/home/users/kinzani/miniconda3/envs/p3/lib/python3.6/site-packages/phonopy/structure/symmetry.py", line 453, in symmetrize_borns_and_epsilon
    site_sym = u_sym.get_site_symmetry(i)
  File "/global/home/users/kinzani/miniconda3/envs/p3/lib/python3.6/site-packages/phonopy/structure/symmetry.py", line 124, in get_site_symmetry
    self._symprec)
  File "/global/home/users/kinzani/miniconda3/envs/p3/lib/python3.6/site-packages/phonopy/structure/symmetry.py", line 174, in _get_site_symmetry
    pos = positions[atom_number]
IndexError: index 2 is out of bounds for axis 0 with size 2
```

**Comment by ajjackson** [comment]
I can reproduce this with the NaCl example from the Phonopy source package. Will take a closer look...

**Comment by ajjackson** [comment]
I think I have fixed this in #58 , can you give that branch a try and report back?

**Comment by kinzani** [comment]
Works a treat. `--primitive-auto` is working nicely also. Cheers Adam!

**Comment by utf** [comment]
Thanks Adam, this looks great.
