### ISSUE TITLE
sumo-bandplot

### ISSUE THREAD

**Issue by Anower120** [SMTG-UCL/sumo#77]
Hi Dr. Alex,
I am having issues with the sumo-bandplot. It gives ["orbital_couloyrs.conf", errors as follows:
Traceback (most recent call last):
  File "/lustre/home/mdhossa55/anaconda3/bin/sumo-bandplot", line 11, in <module>
    load_entry_point('sumo==1.2.0', 'console_scripts', 'sumo-bandplot')()
  File "/lustre/home/mdhossa55/anaconda3/lib/python3.6/site-packages/sumo-1.2.0-py3.6.egg/sumo/cli/bandplot.py", line 521, in
  File "/lustre/home/mdhossa55/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1143, in resource_filen
    self, resource_name
  File "/lustre/home/mdhossa55/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1650, in get_resource_f
    return self._extract_resource(manager, zip_path)
  File "/lustre/home/mdhossa55/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1671, in _extract_resou
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
[OUTCAR.gz](https://github.com/SMTG-UCL/sumo/files/3548675/OUTCAR.gz)

KeyError: 'sumo.plotting/orbital_colours.conf'

How may I get around this orbital_colours.conf error?  I have added my vasprun, OUTCAR and KPOINTS files for your kind supports. Thank you.

Kind regards,
Anower

**Comment by Anower120** [comment]
looks like vasprun file was bigger than 10MB, and failed to upload. I will send those to you via email. Thank you,

**Comment by Anower120** [comment]
> What is the command you are using to plot?

I used **sumo-bandplot** as the command for plotting the band structure.

**Comment by Anower120** [comment]
Is there any solution for the sumo-bandplot related error: 'sumo.plotting/orbital_colours.conf'? Thank you.

**Comment by ajjackson** [comment]
It's not one I've seen before, and it could be related to the Pip packaging (i.e. invisible to people using developer installation!) Can you tell us how you installed Sumo? Has _bandplot_ worked for you in the past or is the first time you've used it?

**Comment by Anower120** [comment]
Thank you for this reply. As suggested in the README file, I used the pip3 command, "pip3 install --user sumo" for installation of SUMO. The sumo-bandplot works for other calculations but does not work for the sent vasprun. 

Would you recommend whether I should install the developer version as well and see whether it gives the same error? Thank you.

**Comment by muhammadaliaskari** [comment]
Hi,
Is it possible to plot projected band structure of a composite having more than 3 atoms?
