### ISSUE TITLE
Projected Bands

### ISSUE THREAD

**Issue by davgumo** [SMTG-UCL/sumo#79]
Hello,
I'm having a problem when trying to plot the fat band structure for an AFM system (CrSb2)

```
sumo-bandplot --ymin -2 --ymax 2 --project Cr.d
```

Then the error is:
```
Traceback (most recent call last):
  File "/home/davgumo/miniconda3/envs/pymatgen/bin/sumo-bandplot", line 10, in <module>
    sys.exit(main())
  File "/home/davgumo/miniconda3/envs/pymatgen/lib/python3.7/site-packages/sumo/cli/bandplot.py", line 548, in main
    dpi=args.dpi, fonts=args.font)
  File "/home/davgumo/miniconda3/envs/pymatgen/lib/python3.7/site-packages/sumo/cli/bandplot.py", line 297, in bandplot
    no_base_style=no_base_style)
  File "/home/davgumo/miniconda3/envs/pymatgen/lib/python3.7/site-packages/sumo/plotting/__init__.py", line 61, in wrapper
    return get_plot(*args, **kwargs)
  File "/home/davgumo/miniconda3/envs/pymatgen/lib/python3.7/site-packages/sumo/plotting/bs_plotter.py", line 400, in get_projected_plot
    lc = rgbline(distances, bands, weights[0], weights[1],
IndexError: index 1 is out of bounds for axis 0 with size 1
```
Any ideas?
Thanks,
David

**Comment by utf** [comment]
You are using the "rgb" plotting mode which requires 3 different orbitals to be set. I.e.

```
sumo-bandplot --ymin -2 --ymax 2 --project Cr.s,Cr.p,Cr.d
```

Alternatively, you can use the "stacked" mode to display a single projection. I.e.,

```
sumo-bandplot --ymin -2 --ymax 2 --project Cr.d --mode stacked
```

For more information, see https://sumo.readthedocs.io/en/latest/sumo-bandplot.html#projected-band-structures

I will update the error messages given by the command to make this more clear!

**Comment by davgumo** [comment]
Thank you guys. Don't know how I missed that.
